### ISSUE TITLE
build script does not work on windows...

### ISSUE THREAD

**Issue by ramstein74** [trainyard/choo-cli#37] opened 2016-10-19 12:30 UTC
build script does not work on windows...

**Comment by YerkoPalma** [comment] 2016-10-19 12:33
Are you getting any output? Please detail your error

**Comment by ramstein74** [comment] 2016-10-19 12:34
[image: Imagem inline 1]

2016-10-19 13:33 GMT+01:00 Yerko Palma notifications@github.com:

**Comment by ramstein74** [comment] 2016-10-19 12:37
this works...in package.json    "build:prod": "scripts\build-prod.sh",

2016-10-19 13:34 GMT+01:00 António Ramos ramstein74@gmail.com:

**Comment by ramstein74** [comment] 2016-10-19 12:40
but the main.js is empty

2016-10-19 13:37 GMT+01:00 António Ramos ramstein74@gmail.com:

**Comment by YerkoPalma** [comment] 2016-10-19 12:42
Oh I see, that is because windows has a different path delimiter than Unix based systems. We had [related issues](https://github.com/trainyard/choo-cli/commit/ea38f20861e7a1954aa3edcf7a35268675b6e5c3#diff-50e3aa130a4f97a42ee2cf111c7b1d9dR9) before

**Comment by seangenabe** [comment] 2016-10-21 07:28
I'm also getting errors on Windows when running `choo new`. I think this one is caused by directly calling the script in `exec`. This should be resolved by calling `node` + the script instead.

**Comment by MattMcFarland** [comment] 2016-11-02 16:04
Would love to fix but I do not develop on windows, pull requests are welcome!!!!

**Comment by MattMcFarland** [comment] 2016-11-18 21:10
@ramstein74 @seangenabe We may have fixed this, when you get a chance install v1.0.0-rc1!  Thanks 👍 

```
npm install choo-cli@v1.0.0-rc1
```

**Comment by rollymaduk** [comment] 2016-11-21 14:25
@MattMcFarland I installed and tested v1.0.0-rc-3 on windows 10 and it seems to work well.

**Comment by MattMcFarland** [comment] 2016-11-21 20:35
Awesome, thank you! I'll close this for now..

**Closed as completed by MattMcFarland** 2016-11-21 20:35 UTC
Labels: bug, help wanted
